apiVersion: apps/v1
kind: Deployment
metadata:
  name: capestone-deploy
  labels:
    app: capstone_app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone_app
  template:
    metadata:
      labels:
        app: capstone_app
    spec:
      containers:
      - name: container-mvn-container
        image: deepak607/healthcare-eta-app
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: banking-np-service
  labels:
    app: capstone_app
spec:
  selector:
    app: capstone_app

  type: NodePort
  ports:
  - nodePort: 31003
    port: 8082
    targetPort: 8082
